name: longread-UMI
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- seqtk=1.3
- parallel=20190522
- racon=1.3.3
# Medaka requires minimap=2.11, not the latest 2.17
- minimap2=2.11
- medaka=0.7.1
- gawk=4.1.3
- cutadapt=2.3
- porechop=0.2.3_seqan2.1.1
- filtlong=0.2.0
- bwa=0.7.17
- samtools=1.9
- bcftools=1.9
